export interface ParisRestaurant {
  id: string;
  nom: string;
  quartier: string;
  arrondissement: string;
  type: string;
  photoId: string;
  description: string;
  scoreViral: number;
  scoreLuxe: number;
  caption: string;
  hashtags: string;
  slides: { titre: string; phrase: string }[];
}

export const RESTAURANTS_PARIS: ParisRestaurant[] = [
  {
    id: "perchoir-marais",
    nom: "Le Perchoir Marais",
    quartier: "Marais",
    arrondissement: "11e",
    type: "Rooftop Bar",
    photoId: "1519864600265-abb23847ef5b",
    description: "Rooftop iconique vue panoramique sur Paris",
    scoreViral: 9.2,
    scoreLuxe: 8.0,
    caption: "🌅 Paris comme tu ne l'as jamais vécu. Le Perchoir Marais t'attend pour nos prochains dîners exclusifs. Gratuit. Sélectif. Inoubliable.",
    hashtags: "#leperchoir #rooftopparis #marais #nightlifeparis #sunset",
    slides: [
      { titre: "Paris vue d'en haut", phrase: "Le coucher de soleil depuis Le Perchoir — chaque soir un tableau différent" },
      { titre: "Dîner au sommet", phrase: "Cuisine méditerranéenne avec les toits de Paris pour décor" },
      { titre: "L'ambiance qui fait tout", phrase: "Musique curatée, lumières tamisées, cercle très select" },
      { titre: "Rejoins le prochain dîner", phrase: "Places limitées — envoie-nous un DM pour candidater" },
    ],
  },
  {
    id: "girafe",
    nom: "Girafe Restaurant",
    quartier: "Trocadéro",
    arrondissement: "16e",
    type: "Gastronomique",
    photoId: "1503917988258-f87a78e3c995",
    description: "Vue imprenable sur la Tour Eiffel",
    scoreViral: 9.5,
    scoreLuxe: 9.2,
    caption: "🗼 La Tour Eiffel comme toile de fond. Notre prochain dîner chez Girafe sera inoubliable. Places très limitées.",
    hashtags: "#giraferestaurant #toureiffel #trocadero #luxeparis #gastronomie",
    slides: [
      { titre: "La Tour Eiffel en fond", phrase: "Dîner face au monument le plus célèbre du monde" },
      { titre: "Cuisine franco-méditerranéenne", phrase: "Des saveurs qui transportent, une vue qui captive" },
      { titre: "La salle la plus photogénique de Paris", phrase: "Chaque angle est une carte postale" },
      { titre: "Sois des nôtres", phrase: "Réponds à notre story pour rejoindre le prochain dîner privé" },
    ],
  },
  {
    id: "silencio",
    nom: "Silencio Club",
    quartier: "Opéra",
    arrondissement: "2e",
    type: "Club Membres",
    photoId: "1508214751196-bcfd4ca60f91",
    description: "Club conçu par David Lynch — accès ultra-sélectif",
    scoreViral: 9.0,
    scoreLuxe: 9.5,
    caption: "🖤 Silencio — le club imaginé par David Lynch. Notre prochaine soirée privée dans les coulisses de Paris. Accès ultra-sélectif.",
    hashtags: "#silencio #davidlynch #paris #clubparis #nightlifeparis",
    slides: [
      { titre: "Le club le plus secret de Paris", phrase: "Imaginé par David Lynch, réservé aux élus" },
      { titre: "Architecture unique au monde", phrase: "Chaque salle est une œuvre d'art habitée" },
      { titre: "La nuit dans sa version la plus pure", phrase: "Ni vu ni connu, juste ressenti" },
      { titre: "Tu veux entrer ?", phrase: "La liste est fermée. Envoie un DM quand même." },
    ],
  },
  {
    id: "laperouse",
    nom: "Lapérouse",
    quartier: "Saint-Germain",
    arrondissement: "6e",
    type: "Restaurant Historique",
    photoId: "1551218372-a8789b81b253",
    description: "Salons privés historiques depuis 1766",
    scoreViral: 7.8,
    scoreLuxe: 9.5,
    caption: "🕯️ Lapérouse — le rendez-vous secret des Parisiens depuis 1766. Notre prochain dîner privé dans les salons historiques.",
    hashtags: "#laperouse #paris #gastronomie #luxury #saintgermain",
    slides: [
      { titre: "Le restaurant le plus mystérieux de Paris", phrase: "Depuis 1766, Lapérouse garde ses secrets" },
      { titre: "Salons privés hors du temps", phrase: "Chaque cabinet raconte une romance parisienne" },
      { titre: "Cuisine gastronomique dans un décor d'or", phrase: "Velours, bougies et dîner d'exception" },
      { titre: "Une soirée que l'on n'oublie pas", phrase: "Places rares. Accès sur invitation uniquement." },
    ],
  },
  {
    id: "brach",
    nom: "Brach Paris",
    quartier: "Victor Hugo",
    arrondissement: "16e",
    type: "Hôtel / Bar",
    photoId: "1492571350019-22de08371d37",
    description: "Hôtel particulier discret par Philippe Starck",
    scoreViral: 8.0,
    scoreLuxe: 9.0,
    caption: "✨ Brach Paris — là où le luxe discret rencontre l'atmosphère la plus exclusive. Nos événements privés arrivent.",
    hashtags: "#brach #paris16 #luxe #soireeprivee #philippestarck",
    slides: [
      { titre: "Hôtel particulier discret", phrase: "Un palace caché au cœur du 16ème" },
      { titre: "Bar signature", phrase: "Les cocktails les plus photographiés de tout Paris" },
      { titre: "Soirée intime & ultra-triée", phrase: "50 invitées max. Aucune pub. Tout le frisson." },
      { titre: "Ta prochaine soirée", phrase: "Envoie un DM pour rejoindre la liste VIP" },
    ],
  },
  {
    id: "loulou",
    nom: "Loulou Restaurant",
    quartier: "Louvre",
    arrondissement: "1er",
    type: "Terrasse / Jardin",
    photoId: "1473116763249-eb81d4fa6e6e",
    description: "Terrasse au Jardin des Tuileries, vue sur le Louvre",
    scoreViral: 8.8,
    scoreLuxe: 8.0,
    caption: "🌿 Loulou au cœur du Louvre — nos brunchs et dîners dans le jardin le plus chic de Paris.",
    hashtags: "#loulouparis #louvre #tuileries #paris1er #brunch",
    slides: [
      { titre: "Jardin des Tuileries, table dressée", phrase: "Un restaurant suspendu entre Paris et l'art" },
      { titre: "Cuisine italienne chic", phrase: "Les meilleures pâtes fraîches avec le Louvre en fond" },
      { titre: "Terrasse la plus copiée de Paris", phrase: "Parasols blanc, soleil, et compagnie parfaite" },
      { titre: "Notre prochain brunch privé", phrase: "Candidature sur DM uniquement" },
    ],
  },
  {
    id: "terass",
    nom: "Terass Hotel Rooftop",
    quartier: "Montmartre",
    arrondissement: "18e",
    type: "Rooftop Bar",
    photoId: "1502602493604-6018e1c46f7a",
    description: "Vue à 360° sur Montmartre et Paris",
    scoreViral: 9.0,
    scoreLuxe: 8.0,
    caption: "🌇 Terass Hotel — Montmartre au coucher du soleil. Notre prochaine soirée privée : bientôt.",
    hashtags: "#montmartre #rooftopparis #cocktails #paris18 #nightlife",
    slides: [
      { titre: "Montmartre vu du ciel", phrase: "Le rooftop le plus photogénique du 18ème" },
      { titre: "Cocktails au coucher du soleil", phrase: "Quand Sacré-Cœur illumine ton verre" },
      { titre: "Les meilleures personnes de Paris", phrase: "Un cercle sélect qui se retrouve chaque semaine" },
      { titre: "La prochaine fois, c'est toi", phrase: "Réponds à notre story pour rejoindre la liste" },
    ],
  },
  {
    id: "kong",
    nom: "Kong",
    quartier: "Châtelet",
    arrondissement: "1er",
    type: "Bar / Restaurant Design",
    photoId: "1552566626-52f8b828a9d4",
    description: "Restaurant design en verrière au-dessus de la Samaritaine",
    scoreViral: 8.5,
    scoreLuxe: 8.5,
    caption: "🍸 Kong — au sommet de Paris, cocktails et vue sur la Seine. Nos soirées privées reprennent.",
    hashtags: "#kong #paris1er #rooftop #cocktails #design",
    slides: [
      { titre: "Le bar le plus design de Paris", phrase: "Verrière, vue sur Seine et cocktails signature" },
      { titre: "Ambiance Tokyo-Paris", phrase: "Philippe Starck a mélangé les genres — on adore" },
      { titre: "Soirée privée au sommet", phrase: "Vue imprenable, playlist curatée, cercle exclusif" },
      { titre: "Inscris-toi", phrase: "DM pour rejoindre notre liste d'invitations" },
    ],
  },
  {
    id: "lavenue",
    nom: "L'Avenue",
    quartier: "Champs-Élysées",
    arrondissement: "8e",
    type: "Brasserie Luxe",
    photoId: "1484659619872-2cb81cd62a0f",
    description: "Brasserie iconique Avenue Montaigne",
    scoreViral: 8.2,
    scoreLuxe: 9.3,
    caption: "💎 L'Avenue — le rendez-vous des Parisiens qui comptent. Nos dîners exclusifs avenue Montaigne arrivent.",
    hashtags: "#lavenueparis #montaigne #luxe #paris8 #brasserie",
    slides: [
      { titre: "L'adresse des Parisiens qui comptent", phrase: "Avenue Montaigne, là où la mode et la gastronomie se croisent" },
      { titre: "Cuisine française d'exception", phrase: "Des classiques revisités dans un cadre irréprochable" },
      { titre: "La table la plus désirée de Paris", phrase: "Voir et être vu — mais avec du style" },
      { titre: "Soirée exclusive à venir", phrase: "Envoie ton profil Instagram pour candidater" },
    ],
  },
  {
    id: "pink-mamma",
    nom: "Pink Mamma",
    quartier: "Pigalle",
    arrondissement: "9e",
    type: "Restaurant Italien",
    photoId: "1517248135467-4c7edcad34c4",
    description: "5 étages d'ambiance italienne ultra-photogénique",
    scoreViral: 9.3,
    scoreLuxe: 7.5,
    caption: "🍝 Pink Mamma — l'adresse italienne la plus instagrammable de Paris. Notre prochain dîner privé sur 5 étages.",
    hashtags: "#pinkmamma #pigalle #paris9 #italian #instagramparis",
    slides: [
      { titre: "5 étages de rêve italien", phrase: "Du rez-de-chaussée au rooftop, chaque niveau est une surprise" },
      { titre: "Cuisine italienne instagrammable", phrase: "Les pâtes les plus photogéniques de tout Paris" },
      { titre: "Le spot préféré des créatrices de contenu", phrase: "Parce que la beauté mérite d'être partagée" },
      { titre: "Notre prochain dîner privé", phrase: "Étage VIP. Accès sur invitation. DM pour candidater." },
    ],
  },
  {
    id: "septime",
    nom: "Septime",
    quartier: "Bastille",
    arrondissement: "11e",
    type: "Bistronomie",
    photoId: "1466978913421-dad2ebd01d17",
    description: "Le temple de la bistronomie parisienne",
    scoreViral: 8.0,
    scoreLuxe: 8.5,
    caption: "🌿 Septime — la table bistronomique la plus convoitée de Paris. Nos dîners privés dans le 11ème sont de retour.",
    hashtags: "#septime #bistronomie #bastille #paris11 #gastronomie",
    slides: [
      { titre: "La table la plus difficile à avoir", phrase: "Réservations complètes 6 semaines à l'avance... sauf pour toi" },
      { titre: "Bistronomie à son sommet", phrase: "Produits de saison, créativité, aucun compromis" },
      { titre: "L'adresse des fins gourmets", phrase: "Michelin, Gault&Millau — et surtout toi" },
      { titre: "Notre soirée privée à Septime", phrase: "Menu dégustation exclusif. DM pour participer." },
    ],
  },
  {
    id: "le-baron",
    nom: "Le Baron Club",
    quartier: "Champs-Élysées",
    arrondissement: "8e",
    type: "Club Légendaire",
    photoId: "1529636798458-a8ed4d2c15de",
    description: "Le club légendaire de la nuit parisienne",
    scoreViral: 8.8,
    scoreLuxe: 8.8,
    caption: "🖤 Le Baron — le club qui a changé la nuit parisienne. Notre prochaine soirée privée : réservé à nos membres.",
    hashtags: "#lebaron #clubparis #nuitparisienne #paris8 #nightclub",
    slides: [
      { titre: "Le club qui a tout changé", phrase: "Depuis 2004, Le Baron définit la nuit parisienne" },
      { titre: "Playlist de légende", phrase: "Les meilleurs DJs du monde dans 200m²" },
      { titre: "L'entrée la plus sélective de Paris", phrase: "Tu ne rentres pas au Baron. On t'invite." },
      { titre: "Tu fais partie des nôtres ?", phrase: "Envoie un DM pour rejoindre la prochaine soirée membres" },
    ],
  },
  {
    id: "costes",
    nom: "Costes Paris",
    quartier: "Louvre",
    arrondissement: "1er",
    type: "Hôtel / Café",
    photoId: "1527361455-5a1f43a7a103",
    description: "L'hôtel le plus chic du 1er arrondissement",
    scoreViral: 8.5,
    scoreLuxe: 9.0,
    caption: "☕ Costes Paris — l'hôtel où Paris se retrouve. Nos petits-déjeuners et dîners exclusifs sont ouverts.",
    hashtags: "#costesparis #paris1er #hotelcostes #luxe #mode",
    slides: [
      { titre: "L'hôtel où Paris se retrouve", phrase: "Fashion week, artistes, people — et toi" },
      { titre: "Bar signé Jacques Garcia", phrase: "Velours rouge, lumières chaudes, cocktails signature" },
      { titre: "Terrasse secrète", phrase: "La cour intérieure la plus copiée de Paris" },
      { titre: "Notre prochain événement Costes", phrase: "DM pour te retrouver dans la liste" },
    ],
  },
  {
    id: "lutetia",
    nom: "Brasserie Lutetia",
    quartier: "Saint-Germain",
    arrondissement: "6e",
    type: "Brasserie Palace",
    photoId: "1414235077428-338989a2e8c0",
    description: "La brasserie du palace Lutetia, rouvert en 2018",
    scoreViral: 7.5,
    scoreLuxe: 9.5,
    caption: "🦪 Lutetia Paris — notre prochaine soirée gastronomique dans ce palace historique. Candidatures ouvertes.",
    hashtags: "#lutetia #palace #saintgermain #brasserie #gastronomie",
    slides: [
      { titre: "L'hôtel des artistes depuis 1910", phrase: "Picasso, Hemingway, Gainsbourg — tous ont dormi ici" },
      { titre: "Brasserie d'exception", phrase: "Les meilleures huîtres et le champagne en abondance" },
      { titre: "Soirée très select", phrase: "30 places. Ambiance feutrée. Tenue de rigueur." },
      { titre: "Candidature ouverte", phrase: "Envoie ton profil Instagram pour participer" },
    ],
  },
  {
    id: "manko",
    nom: "Manko Paris",
    quartier: "Champs-Élysées",
    arrondissement: "8e",
    type: "Club / Restaurant",
    photoId: "1572116469-44eedcec4c4c",
    description: "Restaurant péruvien et club underground, Avenue George V",
    scoreViral: 8.8,
    scoreLuxe: 8.8,
    caption: "🥂 Manko — cuisine péruvienne et club secret au cœur du 8ème. La fête la plus exclusive de Paris.",
    hashtags: "#manko #paris8 #peruvian #clubparis #georgeV",
    slides: [
      { titre: "Dîner. Danser. Recommencer.", phrase: "Chez Manko, la nuit commence à table" },
      { titre: "Cuisine péruvienne d'exception", phrase: "Ceviche, pisco sour et ambiance électrique" },
      { titre: "Le club le mieux caché de Paris", phrase: "Avenue George V — tu passes devant sans le voir" },
      { titre: "Notre prochaine soirée Manko", phrase: "Table VIP + accès club. DM maintenant." },
    ],
  },
];
